spin_version = "1"
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = ""
name = "goodbye"
trigger = { type = "composite", http-base = "/" }
version = "0.1.0"

[[component]]
id = "itowlsontest"
source = "target/wasm32-wasi/release/guest.wasm"
[component.trigger]
type = "sqs"
queue_url = "https://sqs.us-west-2.amazonaws.com/177456779558/itowlsontest"
[component.build]
command = "cargo build --target wasm32-wasi --release"

[[component]]
id = "ui"
source = "honka/target/wasm32-wasi/release/honka.wasm"
[component.trigger]
type = "http"
route = "/test1"
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "honka"

[[component]]
id = "api"
source = "honka/target/wasm32-wasi/release/honka.wasm"
[component.trigger]
type = "http"
route = "/test2"
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "honka"
